### ISSUE TITLE
Howto use?

### ISSUE THREAD

**Issue by davoodkharmanzar** [teak421/SmoothZoom#1]
hi,
thanks for this plugin.
but howto use this exactly??
can i use keyboard to control zoom? is it possible to control DOF too?

**Comment by teak421** [comment]
Hi there... Apologies for the delayed response.  I'm going to create a youtube tutorial shortly to better explain the plugin.  I should have completed by the end of this week if not sooner.  Thanks!

**Comment by teak421** [comment]
Join the Discord channel here if you still need help... I can do a stream and walk you through how to install... Thanks!  

https://discord.gg/q2T6jyJ
