### ISSUE TITLE
CineCameraActor -> SmoothZoom

### ISSUE THREAD

**Issue by johnsmakar** [teak421/SmoothZoom#7]
Hello, I am using this plugin in junction with UE4Duino to read the serial from my hardware device to control the Focal Length of a CineCameraActor in the Level BP.

Is there any way to feed SmoothZoom a stream of (integer) focal lengths and smooth the output?

**Comment by teak421** [comment]
Apologies for the delay... Just saw this.  No, there is no way to feed in an INT for focal lengths at this time.  The source code is available so feel free to modify it as you see fit.  This is a pretty small use case...
